apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wizard-client-webui.configmapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wizard-client-webui.labels" . | nindent 4 }}
data:
  backend_url: "{{ .Values.configMap.backendUrl }}"
  frontend_url: "{{ .Values.configMap.frontendUrl }}"
  cluster_wizard_host: "{{ .Values.configMap.clusterWizardHost }}"
  cluster_wizard_port: "{{ .Values.configMap.clusterWizardPort }}"