apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "iso-repo-server.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      client_max_body_size 20G;

      # Default Page
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        autoindex on;
      }

      # Ubuntu Repo Configuration
      location = /repo-update {
        root /usr/share/nginx/html;
        rewrite ^ /repo_update.html break;
      }

      location = /repo-history {
        root /usr/share/nginx/html;
        rewrite ^ /repo_history.html break;
      }

      location /ubuntu-repo {
        root /mnt;
        autoindex on;
        autoindex_format html;
        add_before_body /autoindex_style.html;
        index off;
      }

      # ISO Server Configuration
      location = /iso-upload {
        root /usr/share/nginx/html;
        rewrite ^ /iso_upload.html break;
      }

      location = /iso-history {
        root /usr/share/nginx/html;
        rewrite ^ /iso_history.html break;
      }

      location = /iso-mapping {
        root /usr/share/nginx/html;
        rewrite ^ /iso_mapping.html break;
      }

      location /iso-files {
        root /mnt/iso-storage;
        autoindex on;
        autoindex_format html;
        add_before_body /autoindex_style.html;
        index off;
      }

      location /iso-extracted {
        root /mnt/iso-storage;
        autoindex on;
        autoindex_format html;
        add_before_body /autoindex_style.html;
        index off;
      }

      # Flask Backend API
      location /api/ {
        proxy_pass http://127.0.0.1:{{ .Values.flask.port }}/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        send_timeout 300s;
      }
    }

