{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.ingress.tls -}}
{{- if eq .Values.expose.ingress.controller "gce" }}
  {{- $_ := set . "path_type" "ImplementationSpecific" -}}
  {{- $_ := set . "path" "/*" -}}
{{- else if eq .Values.expose.ingress.controller "ncp" }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "path" "/.*" -}}
{{- else }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "path" "/" -}}
{{- end }}


---
{{- if semverCompare "<1.14-0" (include "cluster-wizard.ingress.kubeVersion" .) }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" (include "cluster-wizard.ingress.kubeVersion" .) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "cluster-wizard.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cluster-wizard.labels" . | nindent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
    haproxy.org/server-proto: "h2-ssl"
{{- if eq .Values.expose.ingress.controller "ncp" }}
    ncp/use-regex: "true"
{{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  rules:
  - http:
      paths:
{{- if semverCompare "<1.19-0" (include "cluster-wizard.ingress.kubeVersion" .) }}
      - path: {{ .path }}
        backend:
          serviceName: {{ include "cluster-wizard.service" . }}
          servicePort: 50001
{{- else }}
      - path: {{ .path }}
        pathType: {{ .path_type }}
        backend:
          service:
            name: {{ include "cluster-wizard.service" . }}
            port:
              number: 50001
{{- end }}
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- end }}
