apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cluster-wizard.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io