apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-client-webui.configmapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "node-client-webui.labels" . | nindent 4 }}
data:
  backend_url: "{{ .Values.configMap.backendUrl }}"
  frontend_url: "{{ .Values.configMap.frontendUrl }}"
