{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.ingress.tls -}}
{{- if eq .Values.expose.ingress.controller "gce" }}
  {{- $_ := set . "path_type" "ImplementationSpecific" -}}
  {{- $_ := set . "front_path" "/*" -}}
  {{- $_ := set . "back_path" "/backend/*" -}}
{{- else if eq .Values.expose.ingress.controller "ncp" }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "front_path" "/.*" -}}
  {{- $_ := set . "back_path" "/backend/.*" -}}
{{- else }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "front_path" "/" -}}
  {{- $_ := set . "back_path" "/backend/" -}}
{{- end }}

{{- if and (not (eq .Values.expose.ingress.tls.certSource "none")) (not (eq .Values.expose.ingress.tls.certSource "secret")) }}
{{ fail "Invalid certSource option: Allowed values are \"secret\" or \"none\"" }}
{{- end }}

---
{{- if semverCompare "<1.14-0" (include "node-client-webui.ingress.kubeVersion" .) }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" (include "node-client-webui.ingress.kubeVersion" .) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "node-client-webui.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "node-client-webui.labels" . | nindent 4 }}
{{- if or .Values.expose.ingress.tls.clusterIssuer $ingress.annotations }}
  annotations:
{{- if .Values.expose.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: "{{ .Values.expose.ingress.tls.clusterIssuer }}"
{{- end }}
{{- if $ingress.annotations }}
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.expose.internalTLS.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- end }}
{{- if eq .Values.expose.ingress.controller "ncp" }}
    ncp/use-regex: "true"
    {{- if $tls.enabled }}
    ncp/http-redirect: "true"
    {{- end }}
{{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if and $tls.enabled (eq .Values.expose.ingress.tls.certSource "secret") }}
  tls:
  - secretName: {{ .Values.expose.ingress.tls.secretName }}
    {{- if $ingress.host }}
    hosts:
    - {{ $ingress.host }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
{{- if semverCompare "<1.19-0" (include "node-client-webui.ingress.kubeVersion" .) }}
      - path: {{ .front_path }}
        backend:
          serviceName: {{ include "node-client-webui.service" . }}
          servicePort: 25080
      - path: {{ .back_path }}
        backend:
          serviceName: {{ include "node-client-webui.service" . }}
          servicePort: 23051
{{- else }}
      - path: {{ .front_path }}
        pathType: {{ .path_type }}
        backend:
          service:
            name: {{ include "node-client-webui.service" . }}
            port:
              number: 25080
      - path: {{ .back_path }}
        pathType: {{ .path_type }}
        backend:
          service:
            name: {{ include "node-client-webui.service" . }}
            port:
              number: 23051
{{- end }}
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- end }}
