apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "node-client-webui.volumeClaim" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "2Gi" }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}
