apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-client-webui.secretCredential" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}